import type { Config } from '@jest/types';

const config: Config.InitialOptions = {
  collectCoverage: false,
  collectCoverageFrom: [
    // all TypeScript files
    '**/*.ts',
    //
    // except non-testable files
    '!<rootDir>/src/internal/enums/*',
    '!<rootDir>/src/internal/testing/*',
    '!<rootDir>/src/internal/constants/*',
    //
    // except autogenerated files
    '!**/index.ts',
    '!**/api.ts'
  ],
  globals: {
    'ts-jest': {
      tsconfig: 'tsconfig.spec.json'
    }
  },
  moduleFileExtensions: ['js', 'json', 'ts'],
  roots: ['<rootDir>/src'],
  setupFilesAfterEnv: ['./jest.setup.ts'],
  testRegex: '(\\.|/)(spec)\\.ts$',
  transform: {
    '^.+\\.ts$': 'ts-jest'
  },
  verbose: true
};
export default config;
