import type { Config } from '@jest/types';

const baseConfig: Config.InitialOptions = {
  rootDir: './',
  roots: ['<rootDir>/'],
  globals: {
    'ts-jest': {
      tsconfig: '<rootDir>/tsconfig.test.json'
    }
  },
  transform: {
    '^.+\\.(ts)$': 'ts-jest'
  },
  preset: 'ts-jest',
  testRegex: '\\.spec\\.ts$',
  moduleFileExtensions: ['ts', 'js'],
  extensionsToTreatAsEsm: ['.ts'],
  moduleNameMapper: {
    'packages/(.*)': ['<rootDir>/$1']
    // rxjs: ['<rootDir>/../node_modules/rxjs']
  },

  // projects: [
  //   {
  //     displayName: 'common',
  //     testMatch: ['<rootDir>/common/src/**/*.spec.ts']
  //   },
  //   {
  //     displayName: 'native',
  //     testMatch: ['<rootDir>/native/src/**/*.spec.ts']
  //   },
  //   {
  //     displayName: 'rxjs',
  //     testMatch: ['<rootDir>/rxjs/src/**/*.spec.ts']
  //   },
  //   {
  //     displayName: 'testing',
  //     testMatch: ['<rootDir>/testing/src/**/*.spec.ts']
  //   }
  // ],
  verbose: true
  // collectCoverageFrom: [
  //   // all TypeScript files
  //   '**/*.ts',
  //   //
  //   // except non-testable files
  //   '!<rootDir>/src/internal/enums/*',
  //   '!<rootDir>/src/internal/testing/*',
  //   '!<rootDir>/src/internal/constants/*',
  //   //
  //   // except autogenerated files
  //   '!**/index.ts',
  //   '!**/api.ts'
  // ]
};

export default baseConfig;
