import type { Config } from '@jest/types';
import { defaults as tsJestDefaultPreset } from 'ts-jest/presets';

const transpilingOptions: Config.InitialOptions = {
  testTimeout: 10_000,
  transform: {
    ...tsJestDefaultPreset.transform
  },
  testEnvironment: 'jsdom',
  moduleNameMapper: {
    'packages/(.*)': ['<rootDir>/$1']
  },
  extensionsToTreatAsEsm: ['.ts']
};

const baseConfig: Config.InitialOptions = {
  ...transpilingOptions,
  rootDir: './',
  roots: ['<rootDir>/'],
  globals: {
    'ts-jest': {
      tsconfig: '<rootDir>/../tsconfig.test.json'
    }
  },
  coverageDirectory: '<rootDir>/../coverage',
  preset: 'ts-jest/presets/js-with-babel',
  testRegex: '\\.spec\\.ts$',
  moduleFileExtensions: ['ts', 'js'],
  extensionsToTreatAsEsm: ['.ts'],
  projects: [
    {
      ...transpilingOptions,
      displayName: 'internal',
      testRegex: '\\/internal\\/src\\/.*\\.spec\\.ts$'
    },
    {
      ...transpilingOptions,
      displayName: 'native',
      testRegex: '\\/event-bus-native\\/src\\/.*\\.spec\\.ts$'
    },
    {
      ...transpilingOptions,
      displayName: 'rxjs',
      testRegex: '\\/event-bus-rxjs\\/src\\/.*\\.spec\\.ts$'
    },
    {
      ...transpilingOptions,
      displayName: 'rxjs-operators',
      testRegex: '\\/rxjs-operators\\/src\\/.*\\.spec\\.ts$'
    },
    {
      ...transpilingOptions,
      displayName: 'testing',
      testRegex: '\\/testing\\/src\\/.*\\.spec\\.ts$'
    }
  ],
  verbose: true,
  collectCoverageFrom: [
    '**/*.ts', // all TypeScript files
    '!**/*.enum.ts', // except non-testable files
    '!**/*.const.ts', // except non-testable files
    '!**/*.interface.ts', // except non-testable files
    '!**/*.type.ts', // except non-testable files
    '!jest.config-base.ts', // except config files
    '!jest.config-pipeline.ts', // except config files
    '!jest.config.ts', // except config files
    '!**/*.spec.ts', // except test files
    '!**/index.ts', // except autogenerated files
    '!**/api.ts', // except autogenerated files
    '!**/testing/src/**/*.ts', // except testing tools
    '!**/*.alias.ts' // except reexports
  ]
};

export default baseConfig;
